# Homebrew
export PATH="/opt/homebrew/bin:/opt/homebrew/sbin:$PATH"
export PATH="/opt/homebrew/opt/ruby/bin:/opt/homebrew/opt/openjdk/bin:$PATH"

# Nix profiles
export PATH="/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:$PATH"

if [ -e /etc/bashrc ]; then
  . /etc/bashrc
fi
